import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { hashPassword } from "@/lib/auth";

export async function POST() {
  if (process.env.NODE_ENV === "production") {
    return NextResponse.json({ error: "Not allowed in production" }, { status: 403 });
  }

  await prisma.inquiryItem.deleteMany();
  await prisma.inquiry.deleteMany();
  await prisma.product.deleteMany();

  const existing = await prisma.admin.findUnique({ where: { username: "admin" } });
  if (!existing) {
    const password = await hashPassword("admin123");
    await prisma.admin.create({ data: { username: "admin", password } });
  }

  await prisma.product.createMany({
    data: [
      // ── Air Circulator ────────────────────────────────────────────
      {
        name: "Air Circulator Fan FX-L35R",
        nameZh: "空气循环扇 FX-L35R",
        description: "Entry-level floor-standing air circulator with 6616 aluminum motor. Remote control, 3-speed, 3D auto-oscillation, 12h timer, digital display, auto-off screen, aroma function, mosquito-killer holder. Easy-clean removable grille, 3 adjustable heights. Noise level < 59dB.",
        descriptionZh: "入门级落地空气循环扇，6616铝制电机，遥控控制，3档风速，3D立体摇头，12小时定时，数字显示屏，自动关屏，香薰功能，附捕蚊器托架，可拆洗风格，3档高度可调，噪音<59dB。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L35R/main.png",
          "/products/air-circulator/FX-L35R/detail-1.png",
          "/products/air-circulator/FX-L35R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L35R",
          "FOB Price (Ningbo)": "USD 12.5",
          "Rated Power": "50W",
          "Voltage": "220-240V / 50-60Hz",
          "Grille Diameter": "255mm / 10\"",
          "Wind Speed": "5.8 m/s",
          "Motor": "6616 Aluminum",
          "Control": "Remote",
          "Timer": "12 hours",
          "Net Weight": "3.6 kg",
          "Gross Weight": "4.1 kg",
          "Product Dim.": "300×300×1000mm",
          "Package Dim.": "595×235×335mm",
          "40HQ Qty": "1480 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L35R",
          "FOB价格（宁波）": "USD 12.5",
          "额定功率": "50W",
          "电压": "220-240V / 50-60Hz",
          "风格直径": "255mm / 10\"",
          "风速": "5.8 m/s",
          "电机": "6616铝制电机",
          "控制方式": "遥控",
          "定时": "12小时",
          "净重": "3.6 kg",
          "毛重": "4.1 kg",
          "产品尺寸": "300×300×1000mm",
          "包装尺寸": "595×235×335mm",
          "40尺柜装箱量": "1480台",
        }),
        isActive: true,
      },
      {
        name: "Air Circulator Fan FX-L36R",
        nameZh: "空气循环扇 FX-L36R",
        description: "Entry-level floor-standing air circulator with 6616 aluminum motor. Remote control, 3-speed, 3D auto-oscillation, 12h timer, digital display, aroma function, mosquito-killer holder. Easy-clean removable grille, 3 adjustable heights. Noise level < 59dB.",
        descriptionZh: "入门级落地空气循环扇，6616铝制电机，遥控控制，3档风速，3D立体摇头，12小时定时，数字显示，香薰功能，附捕蚊器托架，可拆洗风格，3档高度可调，噪音<59dB。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L36R/main.png",
          "/products/air-circulator/FX-L36R/detail-1.png",
          "/products/air-circulator/FX-L36R/detail-2.png",
          "/products/air-circulator/FX-L36R/detail-3.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L36R",
          "FOB Price (Ningbo)": "USD 10.0",
          "Rated Power": "50W",
          "Voltage": "220-240V / 50-60Hz",
          "Grille Diameter": "255mm / 10\"",
          "Wind Speed": "5.8 m/s",
          "Motor": "6616 Aluminum",
          "Control": "Remote",
          "Timer": "12 hours",
          "Net Weight": "3.7 kg",
          "Gross Weight": "4.2 kg",
          "Product Dim.": "300×300×1000mm",
          "Package Dim.": "595×235×335mm",
          "40HQ Qty": "1480 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L36R",
          "FOB价格（宁波）": "USD 10.0",
          "额定功率": "50W",
          "电压": "220-240V / 50-60Hz",
          "风格直径": "255mm / 10\"",
          "风速": "5.8 m/s",
          "电机": "6616铝制电机",
          "控制方式": "遥控",
          "定时": "12小时",
          "净重": "3.7 kg",
          "毛重": "4.2 kg",
          "产品尺寸": "300×300×1000mm",
          "包装尺寸": "595×235×335mm",
          "40尺柜装箱量": "1480台",
        }),
        isActive: true,
      },
      {
        name: "Air Circulator Fan FX-L55R",
        nameZh: "空气循环扇 FX-L55R",
        description: "Entry-level air circulator with 8-speed control and LED light. Remote control, 3D auto-oscillation, 12h timer, auto-off screen, aroma function, mosquito-killer holder. Easy-clean removable grille, 3 adjustable heights. Optional offline voice control.",
        descriptionZh: "入门级空气循环扇，8档风速，LED灯，遥控控制，3D立体摇头，12小时定时，自动关屏，香薰功能，捕蚊器托架，可拆洗风格，3档高度可调，可选离线语音控制。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L55R/main.png",
          "/products/air-circulator/FX-L55R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L55R",
          "FOB Price (Ningbo)": "USD 13.0",
          "Rated Power": "50W",
          "Voltage": "220-240V / 50-60Hz",
          "Grille Diameter": "255mm / 10\"",
          "Wind Speed": "6.2 m/s",
          "Control": "Remote",
          "Speed Control": "8 speeds",
          "Timer": "12 hours",
          "Net Weight": "3.5 kg",
          "Gross Weight": "4.2 kg",
          "Product Dim.": "248×310×1000mm",
          "Package Dim.": "520×265×330mm",
          "40HQ Qty": "1500 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L55R",
          "FOB价格（宁波）": "USD 13.0",
          "额定功率": "50W",
          "电压": "220-240V / 50-60Hz",
          "风格直径": "255mm / 10\"",
          "风速": "6.2 m/s",
          "控制方式": "遥控",
          "风速档位": "8档",
          "定时": "12小时",
          "净重": "3.5 kg",
          "毛重": "4.2 kg",
          "产品尺寸": "248×310×1000mm",
          "包装尺寸": "520×265×330mm",
          "40尺柜装箱量": "1500台",
        }),
        isActive: true,
      },
      {
        name: "Air Circulator Fan FX-L33R",
        nameZh: "空气循环扇 FX-L33R",
        description: "Mid-range floor-standing air circulator with 7114 aluminum motor. 8-speed control, 3D auto-oscillation, LED decorative light, aroma function, mosquito-killer holder. 20cm height-adjustable column. Noise level < 59dB.",
        descriptionZh: "中端落地空气循环扇，7114铝制电机，8档风速，3D立体摇头，LED装饰灯，香薰功能，捕蚊器托架，20cm高度可调，噪音<59dB。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L33R/main.png",
          "/products/air-circulator/FX-L33R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L33R",
          "FOB Price (Ningbo)": "USD 17.0",
          "Rated Power": "50W",
          "Voltage": "220-240V / 50-60Hz",
          "Grille Diameter": "255mm / 10\"",
          "Wind Speed": "7.0 m/s",
          "Motor": "7114 Aluminum",
          "Control": "Remote",
          "Speed Control": "8 speeds",
          "Timer": "12 hours",
          "Net Weight": "5.15 kg",
          "Gross Weight": "6.25 kg",
          "Product Dim.": "320×285×1100mm",
          "Package Dim.": "650×275×351mm",
          "40HQ Qty": "1080 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L33R",
          "FOB价格（宁波）": "USD 17.0",
          "额定功率": "50W",
          "电压": "220-240V / 50-60Hz",
          "风格直径": "255mm / 10\"",
          "风速": "7.0 m/s",
          "电机": "7114铝制电机",
          "控制方式": "遥控",
          "风速档位": "8档",
          "定时": "12小时",
          "净重": "5.15 kg",
          "毛重": "6.25 kg",
          "产品尺寸": "320×285×1100mm",
          "包装尺寸": "650×275×351mm",
          "40尺柜装箱量": "1080台",
        }),
        isActive: true,
      },
      {
        name: "Air Circulator Fan FX-L53R",
        nameZh: "空气循环扇 FX-L53R",
        description: "Mid-range 12\" air circulator with full-body metal grey spray finish. 7114 aluminum motor, 3-speed, 3 wind modes, 3D auto-oscillation, LED light, aroma function, easy-clean grille. Adjustable height. Optional offline voice control.",
        descriptionZh: "中端12英寸空气循环扇，全机体金属灰喷涂，7114铝制电机，3档风速，3种风模式，3D立体摇头，LED灯，香薰功能，可拆洗风格，高度可调，可选离线语音控制。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L53R/main.png",
          "/products/air-circulator/FX-L53R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L53R",
          "FOB Price (Ningbo)": "USD 19.0",
          "Rated Power": "60W",
          "Voltage": "220-240V / 50-60Hz",
          "Grille Diameter": "290mm / 12\"",
          "Wind Speed": "8.0 m/s",
          "Motor": "7114 Aluminum",
          "Control": "Remote",
          "Speed Control": "3 speeds",
          "Wind Modes": "3 modes",
          "Timer": "12 hours",
          "Net Weight": "5.16 kg",
          "Gross Weight": "6.3 kg",
          "Product Dim.": "330×330×1150mm",
          "Package Dim.": "660×360×300mm",
          "40HQ Qty": "960 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L53R",
          "FOB价格（宁波）": "USD 19.0",
          "额定功率": "60W",
          "电压": "220-240V / 50-60Hz",
          "风格直径": "290mm / 12\"",
          "风速": "8.0 m/s",
          "电机": "7114铝制电机",
          "控制方式": "遥控",
          "风速档位": "3档",
          "风模式": "3种",
          "定时": "12小时",
          "净重": "5.16 kg",
          "毛重": "6.3 kg",
          "产品尺寸": "330×330×1150mm",
          "包装尺寸": "660×360×300mm",
          "40尺柜装箱量": "960台",
        }),
        isActive: true,
      },
      {
        name: "Air Circulator Fan FX-L31R",
        nameZh: "空气循环扇 FX-L31R",
        description: "Mid-range 12\" air circulator with full-body metal grey spray finish. 6120 aluminum motor, 8-speed, 3D auto-oscillation, LED light, aroma function, adjustable height. Auto-off screen in 3 minutes. Optional offline voice control.",
        descriptionZh: "中端12英寸空气循环扇，全机体金属灰喷涂，6120铝制电机，8档风速，3D立体摇头，LED灯，香薰功能，高度可调，3分钟自动关屏，可选离线语音控制。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L31R/main.png",
          "/products/air-circulator/FX-L31R/detail-1.jpg",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L31R",
          "FOB Price (Ningbo)": "USD 16.0",
          "Rated Power": "50W",
          "Voltage": "220-240V / 50-60Hz",
          "Grille Diameter": "290mm / 12\"",
          "Wind Speed": "6.5 m/s",
          "Motor": "6120 Aluminum",
          "Control": "Remote",
          "Speed Control": "8 speeds",
          "Timer": "12 hours",
          "Net Weight": "4.5 kg",
          "Gross Weight": "5.2 kg",
          "Product Dim.": "310×310×1100mm",
          "Package Dim.": "630×252×352mm",
          "40HQ Qty": "1210 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L31R",
          "FOB价格（宁波）": "USD 16.0",
          "额定功率": "50W",
          "电压": "220-240V / 50-60Hz",
          "风格直径": "290mm / 12\"",
          "风速": "6.5 m/s",
          "电机": "6120铝制电机",
          "控制方式": "遥控",
          "风速档位": "8档",
          "定时": "12小时",
          "净重": "4.5 kg",
          "毛重": "5.2 kg",
          "产品尺寸": "310×310×1100mm",
          "包装尺寸": "630×252×352mm",
          "40尺柜装箱量": "1210台",
        }),
        isActive: true,
      },
      {
        name: "BLDC Air Circulator Fan FX-L67R-DC",
        nameZh: "直流空气循环扇 FX-L67R-DC",
        description: "Entry-level BLDC air circulator with 24V brushless motor for ultra-quiet, energy-efficient operation. 32-speed control, auto 90° oscillation, LED blade centre light, aroma function, 12h timer. Wide voltage 100-240V for global market. Optional offline voice control.",
        descriptionZh: "入门级直流空气循环扇，24V无刷电机，超静音节能，32档风速，90°自动摇头，叶片中心LED灯，香薰功能，12小时定时，宽电压100-240V全球适用，可选离线语音控制。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L67R-DC/main.png",
          "/products/air-circulator/FX-L67R-DC/detail-1.png",
          "/products/air-circulator/FX-L67R-DC/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L67R-DC",
          "FOB Price (Ningbo)": "USD 16.5",
          "Rated Power": "30W",
          "Voltage": "100-240V / 50-60Hz",
          "Grille Diameter": "255mm / 10\"",
          "Wind Speed": "6.5 m/s",
          "Motor": "24V BLDC",
          "Control": "Remote",
          "Speed Control": "32 speeds",
          "Oscillation": "Auto 90°",
          "Timer": "12 hours",
          "Net Weight": "3.5 kg",
          "Gross Weight": "4.2 kg",
          "Product Dim.": "295×295×1050mm",
          "Package Dim.": "585×232×350mm",
          "40HQ Qty": "1430 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L67R-DC",
          "FOB价格（宁波）": "USD 16.5",
          "额定功率": "30W",
          "电压": "100-240V / 50-60Hz",
          "风格直径": "255mm / 10\"",
          "风速": "6.5 m/s",
          "电机": "24V BLDC直流无刷",
          "控制方式": "遥控",
          "风速档位": "32档",
          "摇头": "自动90°",
          "定时": "12小时",
          "净重": "3.5 kg",
          "毛重": "4.2 kg",
          "产品尺寸": "295×295×1050mm",
          "包装尺寸": "585×232×350mm",
          "40尺柜装箱量": "1430台",
        }),
        isActive: true,
      },
      {
        name: "BLDC Air Circulator Fan FX-L68R-DC",
        nameZh: "直流空气循环扇 FX-L68R-DC",
        description: "Entry-level BLDC air circulator with 24V brushless motor. 32-speed control, auto 90° oscillation, LED blade centre light, 12h timer. Wide voltage 100-240V for global market. Optional offline voice control.",
        descriptionZh: "入门级直流空气循环扇，24V无刷电机，32档风速，90°自动摇头，叶片中心LED灯，12小时定时，宽电压100-240V全球适用，可选离线语音控制。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-L68R-DC/main.png",
          "/products/air-circulator/FX-L68R-DC/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-L68R-DC",
          "FOB Price (Ningbo)": "USD 16.5",
          "Rated Power": "30W",
          "Voltage": "100-240V / 50-60Hz",
          "Grille Diameter": "255mm / 10\"",
          "Wind Speed": "6.5 m/s",
          "Motor": "24V BLDC",
          "Control": "Remote",
          "Speed Control": "32 speeds",
          "Oscillation": "Auto 90°",
          "Timer": "12 hours",
          "Net Weight": "3.6 kg",
          "Gross Weight": "4.3 kg",
          "Product Dim.": "295×295×1050mm",
          "Package Dim.": "585×232×350mm",
          "40HQ Qty": "1430 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-L68R-DC",
          "FOB价格（宁波）": "USD 16.5",
          "额定功率": "30W",
          "电压": "100-240V / 50-60Hz",
          "风格直径": "255mm / 10\"",
          "风速": "6.5 m/s",
          "电机": "24V BLDC直流无刷",
          "控制方式": "遥控",
          "风速档位": "32档",
          "摇头": "自动90°",
          "定时": "12小时",
          "净重": "3.6 kg",
          "毛重": "4.3 kg",
          "产品尺寸": "295×295×1050mm",
          "包装尺寸": "585×232×350mm",
          "40尺柜装箱量": "1430台",
        }),
        isActive: true,
      },
      {
        name: "BLDC Air Circulator Fan FX-DC25R",
        nameZh: "直流空气循环扇 FX-DC25R",
        description: "High-end BLDC air circulator with touch screen and remote. 12-speed, 3D auto-oscillation, 6m wind delivery, aroma function, easy-clean grille, 18cm adjustable height. Full-body spray color finish. Whole Room Vortex Circulation technology.",
        descriptionZh: "高端直流空气循环扇，触控屏+遥控双控，12档风速，3D立体摇头，送风距离6m，香薰功能，可拆洗风格，高度调节18cm，全机喷色，全屋涡流循环技术。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-DC25R/main.png",
          "/products/air-circulator/FX-DC25R/detail-1.png",
          "/products/air-circulator/FX-DC25R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-DC25R",
          "FOB Price (Ningbo)": "USD 23.0",
          "Rated Power": "50W",
          "Voltage": "100-240V / 50Hz",
          "Grille Diameter": "265mm / 10\"",
          "Wind Speed": "7.0 m/s",
          "Motor": "12V BLDC",
          "Control": "Touch + Remote",
          "Speed Control": "12 speeds",
          "Max Wind Delivery": "6 m",
          "Timer": "12 hours",
          "Net Weight": "4.2 kg",
          "Gross Weight": "5.0 kg",
          "Product Dim.": "320×320×1100mm",
          "Package Dim.": "630×200×365mm",
          "40HQ Qty": "1530 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-DC25R",
          "FOB价格（宁波）": "USD 23.0",
          "额定功率": "50W",
          "电压": "100-240V / 50Hz",
          "风格直径": "265mm / 10\"",
          "风速": "7.0 m/s",
          "电机": "12V BLDC直流无刷",
          "控制方式": "触控+遥控",
          "风速档位": "12档",
          "最大送风距离": "6 m",
          "定时": "12小时",
          "净重": "4.2 kg",
          "毛重": "5.0 kg",
          "产品尺寸": "320×320×1100mm",
          "包装尺寸": "630×200×365mm",
          "40尺柜装箱量": "1530台",
        }),
        isActive: true,
      },
      {
        name: "BLDC Air Circulator Fan FX-DC76R",
        nameZh: "直流空气循环扇 FX-DC76R",
        description: "Premium 12\" BLDC air circulator with 24V motor. 16-speed, 5 wind modes (Normal/Natural/Sleeping/Auto/Turbo), wide 3D oscillation (V-120°/H-120°), max wind delivery 9.6m, wind volume 1050m³/h, LED blade light, adjustable height. Optional offline voice control.",
        descriptionZh: "高端12英寸直流空气循环扇，24V无刷电机，16档风速，5种风模式（正常/自然/睡眠/自动/强力），3D大角度摇头（垂直120°/水平120°），最大送风9.6m，风量1050m³/h，叶片LED灯，高度可调，可选离线语音控制。",
        category: "Air Circulator",
        images: JSON.stringify([
          "/products/air-circulator/FX-DC76R/main.png",
          "/products/air-circulator/FX-DC76R/detail-1.png",
          "/products/air-circulator/FX-DC76R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "FX-DC76R",
          "FOB Price (Ningbo)": "USD 23.5",
          "Rated Power": "50W",
          "Voltage": "100-240V / 50-60Hz",
          "Grille Diameter": "300mm / 12\"",
          "Wind Speed": "6.9 m/s",
          "Wind Volume": "1050 m³/h",
          "Motor": "24V BLDC",
          "Control": "Remote",
          "Speed Control": "16 speeds",
          "Wind Modes": "5 modes",
          "Oscillation": "Vertical 120° / Horizontal 120°",
          "Max Wind Delivery": "9.6 m",
          "Blades": "5 × 220mm",
          "Timer": "1–12 hours",
          "Net Weight": "4.5 kg",
          "Gross Weight": "5.7 kg",
          "Product Dim.": "360×340×1150mm",
          "Package Dim.": "720×220×400mm",
          "40HQ Qty": "1100 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "FX-DC76R",
          "FOB价格（宁波）": "USD 23.5",
          "额定功率": "50W",
          "电压": "100-240V / 50-60Hz",
          "风格直径": "300mm / 12\"",
          "风速": "6.9 m/s",
          "风量": "1050 m³/h",
          "电机": "24V BLDC直流无刷",
          "控制方式": "遥控",
          "风速档位": "16档",
          "风模式": "5种",
          "摇头范围": "垂直120° / 水平120°",
          "最大送风距离": "9.6 m",
          "叶片": "5片 × 220mm",
          "定时": "1–12小时",
          "净重": "4.5 kg",
          "毛重": "5.7 kg",
          "产品尺寸": "360×340×1150mm",
          "包装尺寸": "720×220×400mm",
          "40尺柜装箱量": "1100台",
        }),
        isActive: true,
      },

      // ── Cool Fan ──────────────────────────────────────────────────
      {
        name: "Evaporative Air Cooler CF-01R",
        nameZh: "冷风扇 CF-01R",
        description: "4-in-1 evaporative air cooler: cooling, humidifying, purifying and fan. 15L detachable water tank, 2 ice boxes, 3-speed, 3 wind modes, auto oscillation, max wind delivery 9.5m. 4 castors with brake for easy mobility. Water level indicator.",
        descriptionZh: "四合一蒸发式冷风扇：制冷+加湿+净化+送风。15L可拆卸水箱，2个冰晶盒，3档风速，3种风模式，自动摇头，最大送风9.5m，4个带刹车万向轮，水位指示灯。",
        category: "Cool Fan",
        images: JSON.stringify([
          "/products/cool-fan/CF-01R/main.png",
          "/products/cool-fan/CF-01R/detail-1.png",
          "/products/cool-fan/CF-01R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "CF-01R",
          "FOB Price (Ningbo)": "USD 25.0",
          "Rated Power": "100W",
          "Voltage": "220-240V / 50-60Hz",
          "Wind Volume": "1800 m³/h",
          "Wind Speed": "8.0 m/s",
          "Tank Volume": "15 L",
          "Evaporating Speed": "2–3 L/h",
          "Applied Area": "20–30 m²",
          "Control": "Remote",
          "Wind Modes": "3 modes",
          "Max Wind Delivery": "9.5 m",
          "Materials": "ABS + PP",
          "Net Weight": "5.0 kg",
          "Gross Weight": "6.5 kg",
          "Product Dim.": "400×300×800mm",
          "Package Dim.": "450×335×620mm",
          "MOQ": "750 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "CF-01R",
          "FOB价格（宁波）": "USD 25.0",
          "额定功率": "100W",
          "电压": "220-240V / 50-60Hz",
          "风量": "1800 m³/h",
          "风速": "8.0 m/s",
          "水箱容量": "15 L",
          "蒸发速度": "2–3 L/h",
          "适用面积": "20–30 m²",
          "控制方式": "遥控",
          "风模式": "3种",
          "最大送风距离": "9.5 m",
          "材质": "ABS + PP",
          "净重": "5.0 kg",
          "毛重": "6.5 kg",
          "产品尺寸": "400×300×800mm",
          "包装尺寸": "450×335×620mm",
          "最低起订量": "750台",
        }),
        isActive: true,
      },
      {
        name: "Evaporative Air Cooler CF-02R",
        nameZh: "冷风扇 CF-02R",
        description: "Large-capacity 4-in-1 evaporative air cooler for rooms up to 40m². 30L detachable water tank, 2 ice boxes, removable dust filter, 3-speed, 3 wind modes, auto oscillation, max wind delivery 8.5m. 4 castors with brake.",
        descriptionZh: "大容量四合一蒸发式冷风扇，适用面积达40m²。30L可拆卸水箱，2个冰晶盒，可拆卸防尘滤网，3档风速，3种风模式，自动摇头，最大送风8.5m，4个带刹车万向轮。",
        category: "Cool Fan",
        images: JSON.stringify([
          "/products/cool-fan/CF-02R/main.png",
          "/products/cool-fan/CF-02R/detail-1.png",
          "/products/cool-fan/CF-02R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "CF-02R",
          "FOB Price (Ningbo)": "USD 30.0",
          "Rated Power": "100W",
          "Voltage": "220-240V / 50-60Hz",
          "Wind Volume": "2400 m³/h",
          "Wind Speed": "8.8 m/s",
          "Tank Volume": "30 L",
          "Evaporating Speed": "3–4 L/h",
          "Applied Area": "30–40 m²",
          "Control": "Remote",
          "Wind Modes": "3 modes",
          "Max Wind Delivery": "8.5 m",
          "Materials": "ABS + PP",
          "Net Weight": "9.0 kg",
          "Gross Weight": "11.0 kg",
          "Product Dim.": "480×340×1000mm",
          "Package Dim.": "525×387×743mm",
          "MOQ": "930 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "CF-02R",
          "FOB价格（宁波）": "USD 30.0",
          "额定功率": "100W",
          "电压": "220-240V / 50-60Hz",
          "风量": "2400 m³/h",
          "风速": "8.8 m/s",
          "水箱容量": "30 L",
          "蒸发速度": "3–4 L/h",
          "适用面积": "30–40 m²",
          "控制方式": "遥控",
          "风模式": "3种",
          "最大送风距离": "8.5 m",
          "材质": "ABS + PP",
          "净重": "9.0 kg",
          "毛重": "11.0 kg",
          "产品尺寸": "480×340×1000mm",
          "包装尺寸": "525×387×743mm",
          "最低起订量": "930台",
        }),
        isActive: true,
      },
      {
        name: "Evaporative Air Cooler CF-03R",
        nameZh: "冷风扇 CF-03R",
        description: "Compact 4-in-1 evaporative air cooler, ideal for personal or small-room use. 10L water tank, 2 ice boxes, 3-speed, natural wind mode, auto oscillation, max wind delivery 9.5m. 4 castors for easy mobility.",
        descriptionZh: "小型四合一蒸发式冷风扇，适合个人或小空间使用。10L水箱，2个冰晶盒，3档风速，自然风模式，自动摇头，最大送风9.5m，4个万向轮便于移动。",
        category: "Cool Fan",
        images: JSON.stringify([
          "/products/cool-fan/CF-03R/main.png",
          "/products/cool-fan/CF-03R/detail-1.png",
          "/products/cool-fan/CF-03R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "CF-03R",
          "FOB Price (Ningbo)": "USD 15.5",
          "Rated Power": "85W",
          "Voltage": "220-240V / 50-60Hz",
          "Wind Volume": "1800 m³/h",
          "Wind Speed": "7.0 m/s",
          "Tank Volume": "10 L",
          "Evaporating Speed": "1–2 L/h",
          "Applied Area": "10–20 m²",
          "Control": "Remote",
          "Max Wind Delivery": "9.5 m",
          "Materials": "ABS + PP",
          "Net Weight": "3.9 kg",
          "Gross Weight": "4.7 kg",
          "Product Dim.": "235×275×600mm",
          "Package Dim.": "330×280×640mm",
          "MOQ": "1150 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "CF-03R",
          "FOB价格（宁波）": "USD 15.5",
          "额定功率": "85W",
          "电压": "220-240V / 50-60Hz",
          "风量": "1800 m³/h",
          "风速": "7.0 m/s",
          "水箱容量": "10 L",
          "蒸发速度": "1–2 L/h",
          "适用面积": "10–20 m²",
          "控制方式": "遥控",
          "最大送风距离": "9.5 m",
          "材质": "ABS + PP",
          "净重": "3.9 kg",
          "毛重": "4.7 kg",
          "产品尺寸": "235×275×600mm",
          "包装尺寸": "330×280×640mm",
          "最低起订量": "1150台",
        }),
        isActive: true,
      },

      // ── Heater ────────────────────────────────────────────────────
      {
        name: "PTC Ceramic Heater QN816R",
        nameZh: "PTC陶瓷取暖器 QN816R",
        description: "PTC ceramic heater with touch screen and remote. 2 heating levels (1000/2000W), auto oscillation, 20–40°C temperature setting, 12h timer, room temp display, memory function, overheat and tip-over protection. Recessed handle on back. Fire-retardant PP housing.",
        descriptionZh: "PTC陶瓷取暖器，触控屏+遥控，2档加热（1000/2000W），自动摇头，温度可设20–40°C，12小时定时，室温显示，记忆功能，过热保护+倾倒保护，背面凹槽提手，阻燃PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN816R/main.png",
          "/products/heater/QN816R/detail-1.png",
          "/products/heater/QN816R/detail-2.jpg",
        ]),
        specs: JSON.stringify({
          "Model": "QN816R",
          "FOB Price (Ningbo)": "USD 14.5",
          "Rated Power": "1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Touch + Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "1.8 / 2.3 kg",
          "Product Dim.": "230×230×620mm",
          "Package Dim.": "185×185×655mm",
          "MOQ": "3000 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN816R",
          "FOB价格（宁波）": "USD 14.5",
          "额定功率": "1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "触控+遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "1.8 / 2.3 kg",
          "产品尺寸": "230×230×620mm",
          "包装尺寸": "185×185×655mm",
          "最低起订量": "3000台",
        }),
        isActive: true,
      },
      {
        name: "PTC Ceramic Heater QN2531R",
        nameZh: "PTC陶瓷取暖器 QN2531R",
        description: "PTC ceramic heater with dynamic flame display for ambiance. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer, 20–40°C setting, tip-over and overheat protection. Fire-proof PP housing.",
        descriptionZh: "PTC陶瓷取暖器，动态火焰显示效果，3秒即热，2档加热，ECO节能模式，自动摇头，12小时定时，温度可设20–40°C，倾倒保护+过热保护，防火PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2531R/main.png",
          "/products/heater/QN2531R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2531R",
          "FOB Price (Ningbo)": "USD 17.5",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Special Feature": "Dynamic Flame Display",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "2.1 / 2.55 kg",
          "Product Dim.": "215×170×615mm",
          "Package Dim.": "200×172×655mm",
          "MOQ": "3050 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2531R",
          "FOB价格（宁波）": "USD 17.5",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "特色功能": "动态火焰显示",
          "安全保护": "过热保护+倾倒保护",
          "净重": "2.1 / 2.55 kg",
          "产品尺寸": "215×170×615mm",
          "包装尺寸": "200×172×655mm",
          "最低起订量": "3050台",
        }),
        isActive: true,
      },
      {
        name: "Wall-Mounted PTC Heater QN236R",
        nameZh: "壁挂式PTC取暖器 QN236R",
        description: "Wall-mountable PTC ceramic heater with touch screen and remote. 2 heating levels, 12h timer, room temp display, auto-off screen, overheat and tip-over protection. Optional cloth drying rack. Fire-retardant PP housing.",
        descriptionZh: "壁挂式PTC陶瓷取暖器，触控屏+遥控，可上墙安装，2档加热，12小时定时，室温显示，自动关屏，过热保护+倾倒保护，可选晾衣架，阻燃PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN236R/main.png",
          "/products/heater/QN236R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN236R",
          "FOB Price (Ningbo)": "USD 15.5",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Touch + Remote",
          "Mounting": "Wall-mountable",
          "Heating Levels": "2",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "2.0 / 2.5 kg",
          "Product Dim.": "260×125×300mm",
          "Package Dim.": "305×170×388mm",
          "MOQ": "3360 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN236R",
          "FOB价格（宁波）": "USD 15.5",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "触控+遥控",
          "安装方式": "可壁挂",
          "加热档位": "2档",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "2.0 / 2.5 kg",
          "产品尺寸": "260×125×300mm",
          "包装尺寸": "305×170×388mm",
          "最低起订量": "3360台",
        }),
        isActive: true,
      },
      {
        name: "PTC Ceramic Heater QN2607R",
        nameZh: "PTC陶瓷取暖器 QN2607R",
        description: "PTC ceramic heater with dual fan motors for powerful airflow. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer, 20–40°C setting, tip-over and overheat protection. Fire-proof PP housing.",
        descriptionZh: "双电机PTC陶瓷取暖器，风力强劲，3秒即热，2档加热，ECO节能模式，自动摇头，12小时定时，温度可设20–40°C，倾倒保护+过热保护，防火PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2607R/main.png",
          "/products/heater/QN2607R/detail-1.png",
          "/products/heater/QN2607R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2607R",
          "FOB Price (Ningbo)": "USD 16.0",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Fan Motors": "Dual",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "2.8 / 3.6 kg",
          "Product Dim.": "295×105×370mm",
          "Package Dim.": "340×150×425mm",
          "MOQ": "3140 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2607R",
          "FOB价格（宁波）": "USD 16.0",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "风机": "双电机",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "2.8 / 3.6 kg",
          "产品尺寸": "295×105×370mm",
          "包装尺寸": "340×150×425mm",
          "最低起订量": "3140台",
        }),
        isActive: true,
      },
      {
        name: "PTC Ceramic Heater QN2601R",
        nameZh: "PTC陶瓷取暖器 QN2601R",
        description: "Compact entry-level PTC ceramic heater. Instant heating in 3 seconds, 2 heating levels, ECO mode, 12h timer, 20–40°C temperature setting, tip-over and overheat protection. Fire-proof PP housing.",
        descriptionZh: "小型入门PTC陶瓷取暖器，3秒即热，2档加热，ECO节能模式，12小时定时，温度可设20–40°C，倾倒保护+过热保护，防火PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2601R/main.png",
          "/products/heater/QN2601R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2601R",
          "FOB Price (Ningbo)": "USD 9.0",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "1.7 / 2.5 kg",
          "Product Dim.": "169×130×265mm",
          "Package Dim.": "213×175×320mm",
          "MOQ": "5700 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2601R",
          "FOB价格（宁波）": "USD 9.0",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "1.7 / 2.5 kg",
          "产品尺寸": "169×130×265mm",
          "包装尺寸": "213×175×320mm",
          "最低起订量": "5700台",
        }),
        isActive: true,
      },
      {
        name: "PTC Ceramic Heater QN2602R",
        nameZh: "PTC陶瓷取暖器 QN2602R",
        description: "Entry-level PTC ceramic heater with auto oscillation. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer, 20–40°C setting, tip-over and overheat protection. Fire-proof PP housing.",
        descriptionZh: "入门级PTC陶瓷取暖器带自动摇头，3秒即热，2档加热，ECO节能模式，自动摇头，12小时定时，温度可设20–40°C，倾倒保护+过热保护，防火PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2602R/main.png",
          "/products/heater/QN2602R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2602R",
          "FOB Price (Ningbo)": "USD 11.0",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "2.4 / 3.1 kg",
          "Product Dim.": "169×130×410mm",
          "Package Dim.": "213×175×465mm",
          "MOQ": "3920 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2602R",
          "FOB价格（宁波）": "USD 11.0",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "2.4 / 3.1 kg",
          "产品尺寸": "169×130×410mm",
          "包装尺寸": "213×175×465mm",
          "最低起订量": "3920台",
        }),
        isActive: true,
      },
      {
        name: "PTC Ceramic Heater QN2605R",
        nameZh: "PTC陶瓷取暖器 QN2605R",
        description: "Compact round-body PTC ceramic heater with auto oscillation. Instant heating in 3 seconds, 2 heating levels, ECO mode, 12h timer, 20–40°C setting, tip-over and overheat protection. Fire-proof PP housing.",
        descriptionZh: "紧凑圆形PTC陶瓷取暖器，3秒即热，2档加热，ECO节能，自动摇头，12小时定时，温度可设20–40°C，倾倒保护+过热保护，防火PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2605R/main.png",
          "/products/heater/QN2605R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2605R",
          "FOB Price (Ningbo)": "USD 10.5",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "1.5 / 2.3 kg",
          "Product Dim.": "151×151×240mm",
          "Package Dim.": "195×195×295mm",
          "MOQ": "6060 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2605R",
          "FOB价格（宁波）": "USD 10.5",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "1.5 / 2.3 kg",
          "产品尺寸": "151×151×240mm",
          "包装尺寸": "195×195×295mm",
          "最低起订量": "6060台",
        }),
        isActive: true,
      },
      {
        name: "PTC Ceramic Heater QN2606R",
        nameZh: "PTC陶瓷取暖器 QN2606R",
        description: "Tall round-column PTC ceramic heater with auto oscillation. Instant heating in 3 seconds, 2 heating levels, ECO mode, 12h timer, 20–40°C setting, tip-over and overheat protection. Fire-proof PP housing.",
        descriptionZh: "圆柱形PTC陶瓷取暖器，3秒即热，2档加热，ECO节能，自动摇头，12小时定时，温度可设20–40°C，倾倒保护+过热保护，防火PP外壳。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2606R/main.png",
          "/products/heater/QN2606R/detail-1.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2606R",
          "FOB Price (Ningbo)": "USD 12.5",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "2.2 / 2.9 kg",
          "Product Dim.": "151×151×410mm",
          "Package Dim.": "195×195×465mm",
          "MOQ": "3850 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2606R",
          "FOB价格（宁波）": "USD 12.5",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "2.2 / 2.9 kg",
          "产品尺寸": "151×151×410mm",
          "包装尺寸": "195×195×465mm",
          "最低起订量": "3850台",
        }),
        isActive: true,
      },
      {
        name: "Tower PTC Heater QN803R",
        nameZh: "塔式PTC取暖器 QN803R",
        description: "Mid-range tower PTC ceramic heater with decorative flame effect at the base. Instant heating in 3 seconds, 2 heating levels (1100/2200W), auto oscillation, 12h timer, 20–40°C setting, room temp display, tip-over and overheat protection.",
        descriptionZh: "中端塔式PTC陶瓷取暖器，底部火焰装饰效果，3秒即热，2档加热（1100/2200W），自动摇头，12小时定时，温度可设20–40°C，室温显示，倾倒保护+过热保护。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN803R/main.png",
          "/products/heater/QN803R/detail-1.png",
          "/products/heater/QN803R/detail-2.jpg",
        ]),
        specs: JSON.stringify({
          "Model": "QN803R",
          "FOB Price (Ningbo)": "USD 18.5",
          "Rated Power": "1100 / 2200W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Special Feature": "Flame Effect at Base",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "2.5 / 3.2 kg",
          "Product Dim.": "120×145×800mm",
          "Package Dim.": "835×180×220mm",
          "MOQ": "2100 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN803R",
          "FOB价格（宁波）": "USD 18.5",
          "额定功率": "1100 / 2200W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "特色功能": "底部火焰装饰效果",
          "安全保护": "过热保护+倾倒保护",
          "净重": "2.5 / 3.2 kg",
          "产品尺寸": "120×145×800mm",
          "包装尺寸": "835×180×220mm",
          "最低起订量": "2100台",
        }),
        isActive: true,
      },
      {
        name: "Tower PTC Heater QN805R",
        nameZh: "塔式PTC取暖器 QN805R",
        description: "Mid-range tower PTC ceramic heater with touch screen, remote and LED light. 2 heating levels, ECO mode, auto oscillation, 12h timer, 20–40°C setting, room temp display, memory function, overheat and tip-over protection. Recessed handle on back.",
        descriptionZh: "中端塔式PTC陶瓷取暖器，触控屏+遥控+LED灯，2档加热，ECO节能，自动摇头，12小时定时，温度可设20–40°C，室温显示，记忆功能，过热保护+倾倒保护，背面凹槽提手。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN805R/main.png",
          "/products/heater/QN805R/detail-1.png",
          "/products/heater/QN805R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN805R",
          "FOB Price (Ningbo)": "USD 22.5",
          "Rated Power": "1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Touch + Remote",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "4.0 / 5.3 kg",
          "Product Dim.": "860×240×240mm",
          "Package Dim.": "896×282×287mm",
          "MOQ": "900 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN805R",
          "FOB价格（宁波）": "USD 22.5",
          "额定功率": "1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "触控+遥控",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "4.0 / 5.3 kg",
          "产品尺寸": "860×240×240mm",
          "包装尺寸": "896×282×287mm",
          "最低起订量": "900台",
        }),
        isActive: true,
      },
      {
        name: "Bathroom Mirror Heater QN2306R",
        nameZh: "浴室镜取暖器 QN2306R",
        description: "2-in-1 bathroom mirror heater and fan. Wall-mounted, IPX2 water-resistant, touch screen and remote. Quickly dries towels, mirror front panel, 2 heating levels, ECO mode, 12h timer, memory function, overheat protection. Fire-retardant materials.",
        descriptionZh: "二合一浴室镜取暖器，壁挂安装，IPX2防水，触控屏+遥控，快速烘干毛巾，镜面前板设计，2档加热，ECO节能，12小时定时，记忆功能，过热保护，阻燃材料。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2306R/main.png",
          "/products/heater/QN2306R/detail-1.png",
          "/products/heater/QN2306R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2306R",
          "FOB Price (Ningbo)": "USD 23.0",
          "Rated Power": "5 / 1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Touch + Remote",
          "Mounting": "Wall-mounted",
          "IP Rating": "IPX2",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Timer": "12 hours",
          "Safety": "Overheat Protection",
          "Net Weight": "2.3 / 2.9 kg",
          "Product Dim.": "377×371×145mm",
          "Package Dim.": "425×195×415mm",
          "MOQ": "2000 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2306R",
          "FOB价格（宁波）": "USD 23.0",
          "额定功率": "5 / 1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "触控+遥控",
          "安装方式": "壁挂",
          "防水等级": "IPX2",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "定时": "12小时",
          "安全保护": "过热保护",
          "净重": "2.3 / 2.9 kg",
          "产品尺寸": "377×371×145mm",
          "包装尺寸": "425×195×415mm",
          "最低起订量": "2000台",
        }),
        isActive: true,
      },
      {
        name: "Tower PTC Heater QN2305R",
        nameZh: "塔式PTC取暖器 QN2305R",
        description: "Premium tower PTC ceramic heater with LED top light and dual fan motors. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer, 20–40°C setting, room temp display, tip-over and overheat protection.",
        descriptionZh: "高端塔式PTC陶瓷取暖器，顶部LED灯+双电机，3秒即热，2档加热，ECO节能，自动摇头，12小时定时，温度可设20–40°C，室温显示，倾倒保护+过热保护。",
        category: "Heater",
        images: JSON.stringify([
          "/products/heater/QN2305R/main.png",
          "/products/heater/QN2305R/detail-1.png",
          "/products/heater/QN2305R/detail-2.png",
        ]),
        specs: JSON.stringify({
          "Model": "QN2305R",
          "FOB Price (Ningbo)": "USD 32.0",
          "Rated Power": "1000 / 2000W",
          "Voltage": "220-240V / 50Hz",
          "Heater Type": "PTC Ceramic",
          "Control": "Remote",
          "Fan Motors": "Dual",
          "Heating Levels": "2",
          "Temp. Range": "20–40°C",
          "Oscillation": "Auto",
          "Timer": "12 hours",
          "Safety": "Overheat & Tip-over Protection",
          "Net Weight": "4.0 / 5.3 kg",
          "Product Dim.": "860×240×240mm",
          "Package Dim.": "906×282×287mm",
          "MOQ": "960 pcs",
        }),
        specsZh: JSON.stringify({
          "型号": "QN2305R",
          "FOB价格（宁波）": "USD 32.0",
          "额定功率": "1000 / 2000W",
          "电压": "220-240V / 50Hz",
          "加热方式": "PTC陶瓷",
          "控制方式": "遥控",
          "风机": "双电机",
          "加热档位": "2档",
          "温度范围": "20–40°C",
          "摇头": "自动",
          "定时": "12小时",
          "安全保护": "过热保护+倾倒保护",
          "净重": "4.0 / 5.3 kg",
          "产品尺寸": "860×240×240mm",
          "包装尺寸": "906×282×287mm",
          "最低起订量": "960台",
        }),
        isActive: true,
      },
    ],
  });

  return NextResponse.json({ message: "Seeded successfully: 25 products (10 air circulators, 3 cool fans, 12 heaters)" });
}
