/**
 * One-time seed script for Railway PostgreSQL.
 * Run with: node scripts/seed.cjs
 */
require('dotenv').config();
const { Client } = require('pg');
const bcrypt = require('bcryptjs');

const PRODUCTS = [
  { name:"Air Circulator Fan FX-L35R", nameZh:"空气循环扇 FX-L35R", category:"Air Circulator", description:"Entry-level floor-standing air circulator with 6616 aluminum motor. Remote control, 3-speed, 3D auto-oscillation, 12h timer, digital display, auto-off screen, aroma function, mosquito-killer holder. Easy-clean removable grille, 3 adjustable heights. Noise level < 59dB.", descriptionZh:"入门级落地空气循环扇，6616铝制电机，遥控控制，3档风速，3D立体摇头，12小时定时，数字显示屏，自动关屏，香薰功能，附捕蚊器托架，可拆洗风格，3档高度可调，噪音<59dB。", images:JSON.stringify(["/products/air-circulator/FX-L35R/main.png","/products/air-circulator/FX-L35R/detail-1.png","/products/air-circulator/FX-L35R/detail-2.png"]), specs:JSON.stringify({"Model":"FX-L35R","Rated Power":"50W","Voltage":"220-240V / 50-60Hz","Grille Diameter":"255mm / 10\"","Wind Speed":"5.8 m/s","Motor":"6616 Aluminum","Control":"Remote","Timer":"12 hours","Net Weight":"3.6 kg","Product Dim.":"300×300×1000mm"}) },
  { name:"Air Circulator Fan FX-L36R", nameZh:"空气循环扇 FX-L36R", category:"Air Circulator", description:"Entry-level floor-standing air circulator with 6616 aluminum motor. Remote control, 3-speed, 3D auto-oscillation, 12h timer, digital display, aroma function. Easy-clean removable grille, 3 adjustable heights. Noise level < 59dB.", descriptionZh:"入门级落地空气循环扇，6616铝制电机，遥控控制，3档风速，3D立体摇头，12小时定时，数字显示，香薰功能，可拆洗风格，3档高度可调，噪音<59dB。", images:JSON.stringify(["/products/air-circulator/FX-L36R/main.png","/products/air-circulator/FX-L36R/detail-1.png","/products/air-circulator/FX-L36R/detail-2.png","/products/air-circulator/FX-L36R/detail-3.png"]), specs:JSON.stringify({"Model":"FX-L36R","Rated Power":"50W","Voltage":"220-240V / 50-60Hz","Grille Diameter":"255mm / 10\"","Wind Speed":"5.8 m/s","Motor":"6616 Aluminum","Control":"Remote","Timer":"12 hours","Net Weight":"3.7 kg","Product Dim.":"300×300×1000mm"}) },
  { name:"Air Circulator Fan FX-L55R", nameZh:"空气循环扇 FX-L55R", category:"Air Circulator", description:"Entry-level air circulator with 8-speed control and LED light. Remote control, 3D auto-oscillation, 12h timer, auto-off screen, aroma function. Easy-clean removable grille, 3 adjustable heights.", descriptionZh:"入门级空气循环扇，8档风速，LED灯，遥控控制，3D立体摇头，12小时定时，自动关屏，香薰功能，可拆洗风格，3档高度可调。", images:JSON.stringify(["/products/air-circulator/FX-L55R/main.png","/products/air-circulator/FX-L55R/detail-1.png"]), specs:JSON.stringify({"Model":"FX-L55R","Rated Power":"50W","Voltage":"220-240V / 50-60Hz","Grille Diameter":"255mm / 10\"","Wind Speed":"6.2 m/s","Control":"Remote","Speed Control":"8 speeds","Timer":"12 hours","Product Dim.":"248×310×1000mm"}) },
  { name:"Air Circulator Fan FX-L33R", nameZh:"空气循环扇 FX-L33R", category:"Air Circulator", description:"Mid-range floor-standing air circulator with 7114 aluminum motor. 8-speed control, 3D auto-oscillation, LED decorative light, aroma function. 20cm height-adjustable column. Noise level < 59dB.", descriptionZh:"中端落地空气循环扇，7114铝制电机，8档风速，3D立体摇头，LED装饰灯，香薰功能，20cm高度可调，噪音<59dB。", images:JSON.stringify(["/products/air-circulator/FX-L33R/main.png","/products/air-circulator/FX-L33R/detail-1.png"]), specs:JSON.stringify({"Model":"FX-L33R","Rated Power":"50W","Voltage":"220-240V / 50-60Hz","Grille Diameter":"255mm / 10\"","Wind Speed":"7.0 m/s","Motor":"7114 Aluminum","Control":"Remote","Speed Control":"8 speeds","Timer":"12 hours","Product Dim.":"320×285×1100mm"}) },
  { name:"Air Circulator Fan FX-L53R", nameZh:"空气循环扇 FX-L53R", category:"Air Circulator", description:"Mid-range 12\" air circulator with full-body metal grey spray finish. 7114 aluminum motor, 3-speed, 3 wind modes, 3D auto-oscillation, LED light, aroma function. Adjustable height.", descriptionZh:"中端12英寸空气循环扇，全机体金属灰喷涂，7114铝制电机，3档风速，3种风模式，3D立体摇头，LED灯，香薰功能，高度可调。", images:JSON.stringify(["/products/air-circulator/FX-L53R/main.png","/products/air-circulator/FX-L53R/detail-1.png"]), specs:JSON.stringify({"Model":"FX-L53R","Rated Power":"60W","Voltage":"220-240V / 50-60Hz","Grille Diameter":"290mm / 12\"","Wind Speed":"8.0 m/s","Motor":"7114 Aluminum","Control":"Remote","Wind Modes":"3 modes","Timer":"12 hours","Product Dim.":"330×330×1150mm"}) },
  { name:"Air Circulator Fan FX-L31R", nameZh:"空气循环扇 FX-L31R", category:"Air Circulator", description:"Mid-range 12\" air circulator with full-body metal grey spray finish. 6120 aluminum motor, 8-speed, 3D auto-oscillation, LED light, aroma function, adjustable height.", descriptionZh:"中端12英寸空气循环扇，全机体金属灰喷涂，6120铝制电机，8档风速，3D立体摇头，LED灯，香薰功能，高度可调。", images:JSON.stringify(["/products/air-circulator/FX-L31R/main.png","/products/air-circulator/FX-L31R/detail-1.jpg"]), specs:JSON.stringify({"Model":"FX-L31R","Rated Power":"50W","Voltage":"220-240V / 50-60Hz","Grille Diameter":"290mm / 12\"","Wind Speed":"6.5 m/s","Motor":"6120 Aluminum","Control":"Remote","Speed Control":"8 speeds","Timer":"12 hours","Product Dim.":"310×310×1100mm"}) },
  { name:"BLDC Air Circulator Fan FX-L67R-DC", nameZh:"直流空气循环扇 FX-L67R-DC", category:"Air Circulator", description:"Entry-level BLDC air circulator with 24V brushless motor. 32-speed control, auto 90° oscillation, LED blade centre light, aroma function, 12h timer. Wide voltage 100-240V for global market.", descriptionZh:"入门级直流空气循环扇，24V无刷电机，超静音节能，32档风速，90°自动摇头，叶片中心LED灯，香薰功能，12小时定时，宽电压100-240V全球适用。", images:JSON.stringify(["/products/air-circulator/FX-L67R-DC/main.png","/products/air-circulator/FX-L67R-DC/detail-1.png","/products/air-circulator/FX-L67R-DC/detail-2.png"]), specs:JSON.stringify({"Model":"FX-L67R-DC","Rated Power":"30W","Voltage":"100-240V / 50-60Hz","Grille Diameter":"255mm / 10\"","Motor":"24V BLDC","Control":"Remote","Speed Control":"32 speeds","Timer":"12 hours","Product Dim.":"295×295×1050mm"}) },
  { name:"BLDC Air Circulator Fan FX-L68R-DC", nameZh:"直流空气循环扇 FX-L68R-DC", category:"Air Circulator", description:"Entry-level BLDC air circulator with 24V brushless motor. 32-speed control, auto 90° oscillation, LED blade centre light, 12h timer. Wide voltage 100-240V for global market.", descriptionZh:"入门级直流空气循环扇，24V无刷电机，32档风速，90°自动摇头，叶片中心LED灯，12小时定时，宽电压100-240V全球适用。", images:JSON.stringify(["/products/air-circulator/FX-L68R-DC/main.png","/products/air-circulator/FX-L68R-DC/detail-1.png"]), specs:JSON.stringify({"Model":"FX-L68R-DC","Rated Power":"30W","Voltage":"100-240V / 50-60Hz","Grille Diameter":"255mm / 10\"","Motor":"24V BLDC","Control":"Remote","Speed Control":"32 speeds","Timer":"12 hours","Product Dim.":"295×295×1050mm"}) },
  { name:"BLDC Air Circulator Fan FX-DC25R", nameZh:"直流空气循环扇 FX-DC25R", category:"Air Circulator", description:"High-end BLDC air circulator with touch screen and remote. 12-speed, 3D auto-oscillation, 6m wind delivery, aroma function, easy-clean grille, adjustable height. Whole Room Vortex Circulation technology.", descriptionZh:"高端直流空气循环扇，触控屏+遥控双控，12档风速，3D立体摇头，送风距离6m，香薰功能，可拆洗风格，高度调节，全屋涡流循环技术。", images:JSON.stringify(["/products/air-circulator/FX-DC25R/main.png","/products/air-circulator/FX-DC25R/detail-1.png","/products/air-circulator/FX-DC25R/detail-2.png"]), specs:JSON.stringify({"Model":"FX-DC25R","Rated Power":"50W","Voltage":"100-240V / 50Hz","Grille Diameter":"265mm / 10\"","Wind Speed":"7.0 m/s","Motor":"12V BLDC","Control":"Touch + Remote","Speed Control":"12 speeds","Max Wind Delivery":"6 m","Timer":"12 hours","Product Dim.":"320×320×1100mm"}) },
  { name:"BLDC Air Circulator Fan FX-DC76R", nameZh:"直流空气循环扇 FX-DC76R", category:"Air Circulator", description:"Premium 12\" BLDC air circulator with 24V motor. 16-speed, 5 wind modes, wide 3D oscillation (V-120°/H-120°), max wind delivery 9.6m, wind volume 1050m³/h, LED blade light, adjustable height.", descriptionZh:"高端12英寸直流空气循环扇，24V无刷电机，16档风速，5种风模式，3D大角度摇头（垂直120°/水平120°），最大送风9.6m，风量1050m³/h，叶片LED灯，高度可调。", images:JSON.stringify(["/products/air-circulator/FX-DC76R/main.png","/products/air-circulator/FX-DC76R/detail-1.png","/products/air-circulator/FX-DC76R/detail-2.png"]), specs:JSON.stringify({"Model":"FX-DC76R","Rated Power":"50W","Voltage":"100-240V / 50-60Hz","Grille Diameter":"300mm / 12\"","Wind Speed":"6.9 m/s","Wind Volume":"1050 m³/h","Motor":"24V BLDC","Control":"Remote","Speed Control":"16 speeds","Wind Modes":"5 modes","Max Wind Delivery":"9.6 m","Timer":"1–12 hours","Product Dim.":"360×340×1150mm"}) },
  { name:"Evaporative Air Cooler CF-01R", nameZh:"冷风扇 CF-01R", category:"Cool Fan", description:"4-in-1 evaporative air cooler: cooling, humidifying, purifying and fan. 15L detachable water tank, 2 ice boxes, 3-speed, 3 wind modes, auto oscillation, max wind delivery 9.5m. 4 castors with brake.", descriptionZh:"四合一蒸发式冷风扇：制冷+加湿+净化+送风。15L可拆卸水箱，2个冰晶盒，3档风速，3种风模式，自动摇头，最大送风9.5m，4个带刹车万向轮。", images:JSON.stringify(["/products/cool-fan/CF-01R/main.png","/products/cool-fan/CF-01R/detail-1.png","/products/cool-fan/CF-01R/detail-2.png"]), specs:JSON.stringify({"Model":"CF-01R","Rated Power":"100W","Voltage":"220-240V / 50-60Hz","Wind Volume":"1800 m³/h","Tank Volume":"15 L","Evaporating Speed":"2–3 L/h","Applied Area":"20–30 m²","Control":"Remote","Max Wind Delivery":"9.5 m","Product Dim.":"400×300×800mm"}) },
  { name:"Evaporative Air Cooler CF-02R", nameZh:"冷风扇 CF-02R", category:"Cool Fan", description:"Large-capacity 4-in-1 evaporative air cooler for rooms up to 40m². 30L detachable water tank, 2 ice boxes, removable dust filter, 3-speed, 3 wind modes, auto oscillation.", descriptionZh:"大容量四合一蒸发式冷风扇，适用面积达40m²。30L可拆卸水箱，2个冰晶盒，可拆卸防尘滤网，3档风速，3种风模式，自动摇头。", images:JSON.stringify(["/products/cool-fan/CF-02R/main.png","/products/cool-fan/CF-02R/detail-1.png","/products/cool-fan/CF-02R/detail-2.png"]), specs:JSON.stringify({"Model":"CF-02R","Rated Power":"100W","Voltage":"220-240V / 50-60Hz","Wind Volume":"2400 m³/h","Tank Volume":"30 L","Evaporating Speed":"3–4 L/h","Applied Area":"30–40 m²","Control":"Remote","Max Wind Delivery":"8.5 m","Product Dim.":"480×340×1000mm"}) },
  { name:"Evaporative Air Cooler CF-03R", nameZh:"冷风扇 CF-03R", category:"Cool Fan", description:"Compact 4-in-1 evaporative air cooler, ideal for personal or small-room use. 10L water tank, 2 ice boxes, 3-speed, natural wind mode, auto oscillation, max wind delivery 9.5m.", descriptionZh:"小型四合一蒸发式冷风扇，适合个人或小空间使用。10L水箱，2个冰晶盒，3档风速，自然风模式，自动摇头，最大送风9.5m。", images:JSON.stringify(["/products/cool-fan/CF-03R/main.png","/products/cool-fan/CF-03R/detail-1.png","/products/cool-fan/CF-03R/detail-2.png"]), specs:JSON.stringify({"Model":"CF-03R","Rated Power":"85W","Voltage":"220-240V / 50-60Hz","Wind Volume":"1800 m³/h","Tank Volume":"10 L","Evaporating Speed":"1–2 L/h","Applied Area":"10–20 m²","Control":"Remote","Max Wind Delivery":"9.5 m","Product Dim.":"235×275×600mm"}) },
  { name:"PTC Ceramic Heater QN816R", nameZh:"PTC陶瓷取暖器 QN816R", category:"Heater", description:"PTC ceramic heater with touch screen and remote. 2 heating levels (1000/2000W), auto oscillation, 20–40°C temperature setting, 12h timer, room temp display, memory function, overheat and tip-over protection.", descriptionZh:"PTC陶瓷取暖器，触控屏+遥控，2档加热（1000/2000W），自动摇头，温度可设20–40°C，12小时定时，室温显示，记忆功能，过热保护+倾倒保护。", images:JSON.stringify(["/products/heater/QN816R/main.png","/products/heater/QN816R/detail-1.png","/products/heater/QN816R/detail-2.jpg"]), specs:JSON.stringify({"Model":"QN816R","Rated Power":"1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Touch + Remote","Heating Levels":"2","Temp. Range":"20–40°C","Timer":"12 hours","Product Dim.":"230×230×620mm"}) },
  { name:"PTC Ceramic Heater QN2531R", nameZh:"PTC陶瓷取暖器 QN2531R", category:"Heater", description:"PTC ceramic heater with dynamic flame display. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer, tip-over and overheat protection.", descriptionZh:"PTC陶瓷取暖器，动态火焰显示效果，3秒即热，2档加热，ECO节能模式，自动摇头，12小时定时，倾倒保护+过热保护。", images:JSON.stringify(["/products/heater/QN2531R/main.png","/products/heater/QN2531R/detail-1.png"]), specs:JSON.stringify({"Model":"QN2531R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Heating Levels":"2","Temp. Range":"20–40°C","Timer":"12 hours","Special Feature":"Dynamic Flame Display","Product Dim.":"215×170×615mm"}) },
  { name:"Wall-Mounted PTC Heater QN236R", nameZh:"壁挂式PTC取暖器 QN236R", category:"Heater", description:"Wall-mountable PTC ceramic heater with touch screen and remote. 2 heating levels, 12h timer, room temp display, overheat and tip-over protection. Optional cloth drying rack.", descriptionZh:"壁挂式PTC陶瓷取暖器，触控屏+遥控，可上墙安装，2档加热，12小时定时，室温显示，过热保护+倾倒保护，可选晾衣架。", images:JSON.stringify(["/products/heater/QN236R/main.png","/products/heater/QN236R/detail-1.png"]), specs:JSON.stringify({"Model":"QN236R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Touch + Remote","Mounting":"Wall-mountable","Heating Levels":"2","Timer":"12 hours","Product Dim.":"260×125×300mm"}) },
  { name:"PTC Ceramic Heater QN2607R", nameZh:"PTC陶瓷取暖器 QN2607R", category:"Heater", description:"PTC ceramic heater with dual fan motors for powerful airflow. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer.", descriptionZh:"双电机PTC陶瓷取暖器，风力强劲，3秒即热，2档加热，ECO节能模式，自动摇头，12小时定时。", images:JSON.stringify(["/products/heater/QN2607R/main.png","/products/heater/QN2607R/detail-1.png","/products/heater/QN2607R/detail-2.png"]), specs:JSON.stringify({"Model":"QN2607R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Fan Motors":"Dual","Heating Levels":"2","Temp. Range":"20–40°C","Timer":"12 hours","Product Dim.":"295×105×370mm"}) },
  { name:"PTC Ceramic Heater QN2601R", nameZh:"PTC陶瓷取暖器 QN2601R", category:"Heater", description:"Compact entry-level PTC ceramic heater. Instant heating in 3 seconds, 2 heating levels, ECO mode, 12h timer, tip-over and overheat protection.", descriptionZh:"小型入门PTC陶瓷取暖器，3秒即热，2档加热，ECO节能模式，12小时定时，倾倒保护+过热保护。", images:JSON.stringify(["/products/heater/QN2601R/main.png","/products/heater/QN2601R/detail-1.png"]), specs:JSON.stringify({"Model":"QN2601R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Heating Levels":"2","Temp. Range":"20–40°C","Timer":"12 hours","Product Dim.":"169×130×265mm"}) },
  { name:"PTC Ceramic Heater QN2602R", nameZh:"PTC陶瓷取暖器 QN2602R", category:"Heater", description:"Entry-level PTC ceramic heater with auto oscillation. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer.", descriptionZh:"入门级PTC陶瓷取暖器带自动摇头，3秒即热，2档加热，ECO节能模式，自动摇头，12小时定时。", images:JSON.stringify(["/products/heater/QN2602R/main.png","/products/heater/QN2602R/detail-1.png"]), specs:JSON.stringify({"Model":"QN2602R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Heating Levels":"2","Timer":"12 hours","Oscillation":"Auto","Product Dim.":"169×130×410mm"}) },
  { name:"PTC Ceramic Heater QN2605R", nameZh:"PTC陶瓷取暖器 QN2605R", category:"Heater", description:"Compact round-body PTC ceramic heater with auto oscillation. Instant heating in 3 seconds, 2 heating levels, ECO mode, 12h timer.", descriptionZh:"紧凑圆形PTC陶瓷取暖器，3秒即热，2档加热，ECO节能，自动摇头，12小时定时。", images:JSON.stringify(["/products/heater/QN2605R/main.png","/products/heater/QN2605R/detail-1.png"]), specs:JSON.stringify({"Model":"QN2605R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Heating Levels":"2","Timer":"12 hours","Oscillation":"Auto","Product Dim.":"151×151×240mm"}) },
  { name:"PTC Ceramic Heater QN2606R", nameZh:"PTC陶瓷取暖器 QN2606R", category:"Heater", description:"Tall round-column PTC ceramic heater with auto oscillation. Instant heating in 3 seconds, 2 heating levels, ECO mode, 12h timer.", descriptionZh:"圆柱形PTC陶瓷取暖器，3秒即热，2档加热，ECO节能，自动摇头，12小时定时。", images:JSON.stringify(["/products/heater/QN2606R/main.png","/products/heater/QN2606R/detail-1.png"]), specs:JSON.stringify({"Model":"QN2606R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Heating Levels":"2","Timer":"12 hours","Oscillation":"Auto","Product Dim.":"151×151×410mm"}) },
  { name:"Tower PTC Heater QN803R", nameZh:"塔式PTC取暖器 QN803R", category:"Heater", description:"Mid-range tower PTC ceramic heater with decorative flame effect at the base. 2 heating levels (1100/2200W), auto oscillation, 12h timer, room temp display, tip-over and overheat protection.", descriptionZh:"中端塔式PTC陶瓷取暖器，底部火焰装饰效果，2档加热（1100/2200W），自动摇头，12小时定时，室温显示，倾倒保护+过热保护。", images:JSON.stringify(["/products/heater/QN803R/main.png","/products/heater/QN803R/detail-1.png","/products/heater/QN803R/detail-2.jpg"]), specs:JSON.stringify({"Model":"QN803R","Rated Power":"1100 / 2200W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Heating Levels":"2","Special Feature":"Flame Effect at Base","Timer":"12 hours","Product Dim.":"120×145×800mm"}) },
  { name:"Tower PTC Heater QN805R", nameZh:"塔式PTC取暖器 QN805R", category:"Heater", description:"Mid-range tower PTC ceramic heater with touch screen, remote and LED light. 2 heating levels, ECO mode, auto oscillation, 12h timer, memory function, overheat and tip-over protection.", descriptionZh:"中端塔式PTC陶瓷取暖器，触控屏+遥控+LED灯，2档加热，ECO节能，自动摇头，12小时定时，记忆功能，过热保护+倾倒保护。", images:JSON.stringify(["/products/heater/QN805R/main.png","/products/heater/QN805R/detail-1.png","/products/heater/QN805R/detail-2.png"]), specs:JSON.stringify({"Model":"QN805R","Rated Power":"1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Touch + Remote","Heating Levels":"2","Timer":"12 hours","Product Dim.":"860×240×240mm"}) },
  { name:"Bathroom Mirror Heater QN2306R", nameZh:"浴室镜取暖器 QN2306R", category:"Heater", description:"2-in-1 bathroom mirror heater and fan. Wall-mounted, IPX2 water-resistant, touch screen and remote. Quickly dries towels, mirror front panel, 2 heating levels, ECO mode, 12h timer, overheat protection.", descriptionZh:"二合一浴室镜取暖器，壁挂安装，IPX2防水，触控屏+遥控，快速烘干毛巾，镜面前板设计，2档加热，ECO节能，12小时定时，过热保护。", images:JSON.stringify(["/products/heater/QN2306R/main.png","/products/heater/QN2306R/detail-1.png","/products/heater/QN2306R/detail-2.png"]), specs:JSON.stringify({"Model":"QN2306R","Rated Power":"5 / 1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Touch + Remote","Mounting":"Wall-mounted","IP Rating":"IPX2","Heating Levels":"2","Timer":"12 hours","Product Dim.":"377×371×145mm"}) },
  { name:"Tower PTC Heater QN2305R", nameZh:"塔式PTC取暖器 QN2305R", category:"Heater", description:"Premium tower PTC ceramic heater with LED top light and dual fan motors. Instant heating in 3 seconds, 2 heating levels, ECO mode, auto oscillation, 12h timer, room temp display.", descriptionZh:"高端塔式PTC陶瓷取暖器，顶部LED灯+双电机，3秒即热，2档加热，ECO节能，自动摇头，12小时定时，室温显示。", images:JSON.stringify(["/products/heater/QN2305R/main.png","/products/heater/QN2305R/detail-1.png","/products/heater/QN2305R/detail-2.png"]), specs:JSON.stringify({"Model":"QN2305R","Rated Power":"1000 / 2000W","Voltage":"220-240V / 50Hz","Heater Type":"PTC Ceramic","Control":"Remote","Fan Motors":"Dual","Heating Levels":"2","Timer":"12 hours","Product Dim.":"860×240×240mm"}) },
];

async function main() {
  const client = new Client({ connectionString: process.env.DATABASE_URL });
  await client.connect();
  console.log('Connected to Railway PostgreSQL');

  // Check if already seeded
  const { rows: countRows } = await client.query('SELECT COUNT(*) FROM "Product"');
  if (parseInt(countRows[0].count) > 0) {
    console.log(`Database already has ${countRows[0].count} products. Skipping product seed.`);
  } else {
    for (const p of PRODUCTS) {
      await client.query(
        `INSERT INTO "Product" (name, "nameZh", category, description, "descriptionZh", images, specs, "isActive", "createdAt", "updatedAt")
         VALUES ($1,$2,$3,$4,$5,$6,$7,true,NOW(),NOW())`,
        [p.name, p.nameZh, p.category, p.description, p.descriptionZh, p.images, p.specs]
      );
    }
    console.log(`✅ Inserted ${PRODUCTS.length} products`);
  }

  // Admin user
  const { rows: adminRows } = await client.query('SELECT COUNT(*) FROM "Admin"');
  if (parseInt(adminRows[0].count) > 0) {
    console.log('Admin already exists, skipping.');
  } else {
    const hash = await bcrypt.hash('admin123', 10);
    await client.query(
      `INSERT INTO "Admin" (username, password, "createdAt") VALUES ($1,$2,NOW())`,
      ['admin', hash]
    );
    console.log('✅ Admin user created (username: admin, password: admin123)');
  }

  await client.end();
  console.log('\n🎉 Seed complete!');
}

main().catch(err => { console.error(err); process.exit(1); });
